using System;
namespace Persits.PDF
{
	internal enum TiffTags
	{
		TIFF_TAG_PHOTOMETRIC = 262,
		TIFF_TAG_COMPRESSION = 259,
		TIFF_TAG_WIDTH = 256,
		TIFF_TAG_LENGTH,
		TIFF_TAG_STRIPOFFSETS = 273,
		TIFF_TAG_STRIPBYTECOUNTS = 279,
		TIFF_TAG_XRESOLUTION = 282,
		TIFF_TAG_YRESOLUTION,
		TIFF_TAG_RESOLUTIONUNIT = 296,
		TIFF_TAG_ROWSPERSTRIP = 278,
		TIFF_TAG_SAMPLESPERPIXEL = 277,
		TIFF_TAG_EXTRASAMPLES = 338,
		TIFF_TAG_BITSPERSAMPLE = 258,
		TIFF_TAG_COLORMAP = 320,
		TIFF_TAG_PREDICTOR = 317,
		TIFF_TAG_FILLORDER = 266,
		TIFF_TAG_WHITEPOINT = 318,
		TIFF_TAG_PRIMARYCHROM,
		TIFF_TAG_TRANSFERRANGE = 342,
		TIFF_TAG_TRANSFERFUNC = 301,
		TIFF_TAG_REFBLACKWHITE = 532,
		TIFF_TAG_T4OPTIONS = 292,
		TIFF_TAG_PLANARCONFIG = 284
	}
}
