using System;
namespace Persits.PDF
{
	internal enum TiffCompressions
	{
		TIFF_COMPRESSION_NONE = 1,
		TIFF_COMPRESSION_HUFFMAN,
		TIFF_COMPRESSION_GROUP3,
		TIFF_COMPRESSION_GROUP4,
		TIFF_COMPRESSION_LZW,
		TIFF_COMPRESSION_JPEG,
		TIFF_COMPRESSION_PACKBITS = 32773
	}
}
