//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTestClient {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WcfTestClient.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About {0}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding....
        /// </summary>
        internal static string AddingAction {
            get {
                return ResourceManager.GetString("AddingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter the endpoint address:.
        /// </summary>
        internal static string AddServicePrompt {
            get {
                return ResourceManager.GetString("AddServicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Service.
        /// </summary>
        internal static string AddServiceTitle {
            get {
                return ResourceManager.GetString("AddServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version {0}.
        /// </summary>
        internal static string AssemblyVersion {
            get {
                return ResourceManager.GetString("AssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not create the folder &apos;{0}&apos;, please check if you have proper permissions..
        /// </summary>
        internal static string CannotCreateFolder {
            get {
                return ResourceManager.GetString("CannotCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closing ....
        /// </summary>
        internal static string ClosingClientStatus {
            get {
                return ResourceManager.GetString("ClosingClientStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microsoft Corporation.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client.dll.config in the service node &apos;{0}&apos;.
        /// </summary>
        internal static string ConfigChanging {
            get {
                return ResourceManager.GetString("ConfigChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Config File.
        /// </summary>
        internal static string ConfigFileNodeName {
            get {
                return ResourceManager.GetString("ConfigFileNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The configuration file cannot be found. Please refresh your service..
        /// </summary>
        internal static string ConfigNotFound {
            get {
                return ResourceManager.GetString("ConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © Microsoft Corporation.  All rights reserved..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The default configuration file cannot be found..
        /// </summary>
        internal static string DefaultConfigNotFound {
            get {
                return ResourceManager.GetString("DefaultConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The default configuration file does not exist. Please refresh your service and try again..
        /// </summary>
        internal static string DefaultConfigNotFoundDetail {
            get {
                return ResourceManager.GetString("DefaultConfigNotFoundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are going to paste a DataSet object with a different schema..
        /// </summary>
        internal static string DifferentSchemaWarning {
            get {
                return ResourceManager.GetString("DifferentSchemaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The directory &apos;{0}&apos; does not exist, please create it and run again..
        /// </summary>
        internal static string DirectoryNotExist {
            get {
                return ResourceManager.GetString("DirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit....
        /// </summary>
        internal static string EditDataSet {
            get {
                return ResourceManager.GetString("EditDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The endpoint is disabled due to improper configuration settings..
        /// </summary>
        internal static string EndpointError {
            get {
                return ResourceManager.GetString("EndpointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{0} of {1}&quot;.
        /// </summary>
        internal static string ErrorBrowseLocationFormat {
            get {
                return ResourceManager.GetString("ErrorBrowseLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to add a service. Service metadata may not be accessible. Make sure your service is running and exposing metadata..
        /// </summary>
        internal static string ErrorFailedAddingService {
            get {
                return ResourceManager.GetString("ErrorFailedAddingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to refresh the service. Service metadata may not be accessible. Make sure your service is running and exposing metadata..
        /// </summary>
        internal static string ErrorFailedRefreshingService {
            get {
                return ResourceManager.GetString("ErrorFailedRefreshingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL &apos;{0}&apos; is not a valid URL for WCF Service.
        /// </summary>
        internal static string ErrorInvalidUrl {
            get {
                return ResourceManager.GetString("ErrorInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The dependent tool &apos;svcutil.exe&apos; is not found..
        /// </summary>
        internal static string ErrorMetadataToolNotFound {
            get {
                return ResourceManager.GetString("ErrorMetadataToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Wrap.
        /// </summary>
        internal static string ErrorMsgCbText {
            get {
                return ResourceManager.GetString("ErrorMsgCbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service already exists in the current workspace.
        /// </summary>
        internal static string ErrorServiceAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorServiceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The client was unable to retrieve service metadata. Make sure the service is running and exposing metadata..
        /// </summary>
        internal static string ErrorServiceMetadataCannotBeRetrieved {
            get {
                return ResourceManager.GetString("ErrorServiceMetadataCannotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The option file is not writable, therefore, your settings cannot be saved..
        /// </summary>
        internal static string ErrorSettingsNotAccessible {
            get {
                return ResourceManager.GetString("ErrorSettingsNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This service contract is not supported in the WCF Test Client. Refer to product documentation for a list of supported features..
        /// </summary>
        internal static string ErrorUnsupportedContract {
            get {
                return ResourceManager.GetString("ErrorUnsupportedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This operation is not supported in the WCF Test Client.
        /// </summary>
        internal static string ErrorUnsupportedOperation {
            get {
                return ResourceManager.GetString("ErrorUnsupportedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This operation is not supported in the WCF Test Client because it uses type {0}..
        /// </summary>
        internal static string ErrorUnsupportedOperationBecauseOfUnsupportedType {
            get {
                return ResourceManager.GetString("ErrorUnsupportedOperationBecauseOfUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to navigate forward. The data set schema may not have enough key constraint applied on the current relation. Please double check the data set schema..
        /// </summary>
        internal static string FailedToNavigateForward {
            get {
                return ResourceManager.GetString("FailedToNavigateForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to get the system information..
        /// </summary>
        internal static string FailToRunSystemInfo {
            get {
                return ResourceManager.GetString("FailToRunSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Html View.
        /// </summary>
        internal static string HtmlViewTpText {
            get {
                return ResourceManager.GetString("HtmlViewTpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid command line switch..
        /// </summary>
        internal static string InvalidCmdLineSwitch {
            get {
                return ResourceManager.GetString("InvalidCmdLineSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The config file is invalid. Please make sure it has the correct syntax..
        /// </summary>
        internal static string InvalidConfig {
            get {
                return ResourceManager.GetString("InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The contract &apos;{0}&apos; in client configuration does not match the name in service contract, or there is no valid method in this contract..
        /// </summary>
        internal static string InvalidContract {
            get {
                return ResourceManager.GetString("InvalidContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To recover, please manually correct client configuration.
        ///Or restore to default configuration.
        ///Or check &quot;Always regenerate config when launching services&quot; in the Tools -&gt; Options menu, then refresh the service..
        /// </summary>
        internal static string InvalidContractNameAction {
            get {
                return ResourceManager.GetString("InvalidContractNameAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a String must not be null and must be at least one character long..
        /// </summary>
        internal static string InvalidString {
            get {
                return ResourceManager.GetString("InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One-way message is successfully delivered to the service side.
        /// </summary>
        internal static string OneWayMessageDisplay {
            get {
                return ResourceManager.GetString("OneWayMessageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test client for Windows Communication Foundation services.
        ///
        ///Extended by Hernán Javier Hegykozi (hernanjh@gmail.com).
        /// </summary>
        internal static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microsoft WCF Test Client.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proxy Code.
        /// </summary>
        internal static string ProxyCodeNodeName {
            get {
                return ResourceManager.GetString("ProxyCodeNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refreshing....
        /// </summary>
        internal static string RefreshingAction {
            get {
                return ResourceManager.GetString("RefreshingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are about to refresh the service. After refreshing, the service status will be reset. Are you going to continue any way?.
        /// </summary>
        internal static string RefreshServiceWarning {
            get {
                return ResourceManager.GetString("RefreshServiceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string RefreshServiceWarningTitle {
            get {
                return ResourceManager.GetString("RefreshServiceWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The service will be removed..
        /// </summary>
        internal static string RemoveServiceWarning {
            get {
                return ResourceManager.GetString("RemoveServiceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter test case name:.
        /// </summary>
        internal static string RenameTestCasePrompt {
            get {
                return ResourceManager.GetString("RenameTestCasePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename Test Case.
        /// </summary>
        internal static string RenameTestCaseTitle {
            get {
                return ResourceManager.GetString("RenameTestCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Service Projects.
        /// </summary>
        internal static string RootNodeName {
            get {
                return ResourceManager.GetString("RootNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are about to send information over the network. Insecure bindings or malicious services could allow private information to be viewed by others. Do not try to invoke services you do not trust, and use a secure binding if you are transmitting information you do not want others to see..
        /// </summary>
        internal static string SecurityWarning {
            get {
                return ResourceManager.GetString("SecurityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security Warning.
        /// </summary>
        internal static string SecurityWarningTitle {
            get {
                return ResourceManager.GetString("SecurityWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to start Service Configuration Editor. Please make sure Microsoft Windows SDK is correctly installed..
        /// </summary>
        internal static string StartSvcConfigEditorFail {
            get {
                return ResourceManager.GetString("StartSvcConfigEditorFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to add {0} of {1} services. Service metadata may not be accessible. Make sure your service is running and exposing metadata..
        /// </summary>
        internal static string StatusAddingMultipleServicesFailed {
            get {
                return ResourceManager.GetString("StatusAddingMultipleServicesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding service ....
        /// </summary>
        internal static string StatusAddingService {
            get {
                return ResourceManager.GetString("StatusAddingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service added successfully..
        /// </summary>
        internal static string StatusAddingServiceCompleted {
            get {
                return ResourceManager.GetString("StatusAddingServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding service was cancelled..
        /// </summary>
        internal static string StatusAddServiceCancelled {
            get {
                return ResourceManager.GetString("StatusAddServiceCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoking service ....
        /// </summary>
        internal static string StatusInvokingService {
            get {
                return ResourceManager.GetString("StatusInvokingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service invocation completed..
        /// </summary>
        internal static string StatusInvokingServiceCompleted {
            get {
                return ResourceManager.GetString("StatusInvokingServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to invoke the service. Possible causes: The service is offline or inaccessible; the client-side configuration does not match the proxy; the existing proxy is invalid. Refer to the stack trace for more detail. You can try to recover by starting a new proxy, restoring to default configuration, or refreshing the service..
        /// </summary>
        internal static string StatusInvokingServiceFailed {
            get {
                return ResourceManager.GetString("StatusInvokingServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading configuration ....
        /// </summary>
        internal static string StatusLoadingConfig {
            get {
                return ResourceManager.GetString("StatusLoadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration loaded successfully..
        /// </summary>
        internal static string StatusLoadingConfigCompleted {
            get {
                return ResourceManager.GetString("StatusLoadingConfigCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load configuration..
        /// </summary>
        internal static string StatusLoadingConfigFailed {
            get {
                return ResourceManager.GetString("StatusLoadingConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refreshing service ....
        /// </summary>
        internal static string StatusRefreshingService {
            get {
                return ResourceManager.GetString("StatusRefreshingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service refreshed successfully..
        /// </summary>
        internal static string StatusRefreshingServiceCompleted {
            get {
                return ResourceManager.GetString("StatusRefreshingServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refreshing service was cancelled..
        /// </summary>
        internal static string StatusRefreshServiceCancelled {
            get {
                return ResourceManager.GetString("StatusRefreshServiceCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removing service ....
        /// </summary>
        internal static string StatusRemovingService {
            get {
                return ResourceManager.GetString("StatusRemovingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service removed successfully..
        /// </summary>
        internal static string StatusRemovingServiceCompleted {
            get {
                return ResourceManager.GetString("StatusRemovingServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot find Service Configuration Editor. Please make sure Microsoft Windows SDK is correctly installed..
        /// </summary>
        internal static string SvcConfigEditorNotFound {
            get {
                return ResourceManager.GetString("SvcConfigEditorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text View.
        /// </summary>
        internal static string TextViewTpText {
            get {
                return ResourceManager.GetString("TextViewTpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; is not a valid value for this type.
        /// </summary>
        internal static string TypeError {
            get {
                return ResourceManager.GetString("TypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string TypeHeader {
            get {
                return ResourceManager.GetString("TypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usage:
        ///WcfTestClient.exe &lt;one mex or wsdl URL&gt; &lt;additional mex or wsdl URL&gt; &lt;additional mex or wsdl URL&gt; …
        ///WcfTestClient.exe /ProjectPath &lt;Path&gt;
        ///WcfTestClient.exe /RestoreProjectPath.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        internal static string ValueHeader {
            get {
                return ResourceManager.GetString("ValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View....
        /// </summary>
        internal static string ViewDataSet {
            get {
                return ResourceManager.GetString("ViewDataSet", resourceCulture);
            }
        }
    }
}
