//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipro.SourceControlProvider.SiproSCP {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sipro.SourceControlProvider.SiproSCP.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _500 {
            get {
                object obj = ResourceManager.GetObject("500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _501 {
            get {
                object obj = ResourceManager.GetObject("501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press Cancel to cancel this OnApply.  OK to continue.
        /// </summary>
        internal static string ApplyProviderOptions {
            get {
                return ResourceManager.GetString("ApplyProviderOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This package implements the functionalities of a source control provider package..
        /// </summary>
        internal static string Implements {
            get {
                return ResourceManager.GetString("Implements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Managed Sipro Source Control Provider.
        /// </summary>
        internal static string Managed {
            get {
                return ResourceManager.GetString("Managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Managed Sipro Source Control Provider.
        /// </summary>
        internal static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file {0} you are trying to edit is read only on disk. Do you want do make the file writable so you can continue editing it?.
        /// </summary>
        internal static string QEQS_EditUncontrolledReadOnly {
            get {
                return ResourceManager.GetString("QEQS_EditUncontrolledReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checked in.
        /// </summary>
        internal static string Status_CheckedIn {
            get {
                return ResourceManager.GetString("Status_CheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checked out by you.
        /// </summary>
        internal static string Status_CheckedOut {
            get {
                return ResourceManager.GetString("Status_CheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending add.
        /// </summary>
        internal static string Status_PendingAdd {
            get {
                return ResourceManager.GetString("Status_PendingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sipro Source Control Provider ToolWindow.
        /// </summary>
        internal static string ToolWindowCaption {
            get {
                return ResourceManager.GetString("ToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file {0} you are going to delete is a source controlled file. Are you sure you want to continue and delete this file?.
        /// </summary>
        internal static string TPD_DeleteControlledFile {
            get {
                return ResourceManager.GetString("TPD_DeleteControlledFile", resourceCulture);
            }
        }
    }
}
