//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18051
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGen.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGen.Properties.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {AUTHOR}.
        /// </summary>
        internal static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {CLASSTYPE}.
        /// </summary>
        internal static string CLASSTYPE {
            get {
                return ResourceManager.GetString("CLASSTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {CLASSTYPELOWER}.
        /// </summary>
        internal static string CLASSTYPELOWER {
            get {
                return ResourceManager.GetString("CLASSTYPELOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {CONSTRUCTOR}.
        /// </summary>
        internal static string CONSTRUCTOR {
            get {
                return ResourceManager.GetString("CONSTRUCTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {CTORBODY}.
        /// </summary>
        internal static string CTORBODY {
            get {
                return ResourceManager.GetString("CTORBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {CTORPARAMETERS}.
        /// </summary>
        internal static string CTORPARAMETERS {
            get {
                return ResourceManager.GetString("CTORPARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {DATAMEMBERS}.
        /// </summary>
        internal static string DATAMEMBERS {
            get {
                return ResourceManager.GetString("DATAMEMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {DATECREATED}.
        /// </summary>
        internal static string DATECREATED {
            get {
                return ResourceManager.GetString("DATECREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {MAPPER}.
        /// </summary>
        internal static string MAPPER {
            get {
                return ResourceManager.GetString("MAPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {NAMESPACE}.
        /// </summary>
        internal static string NAMESPACE {
            get {
                return ResourceManager.GetString("NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {OBJECTNAME}.
        /// </summary>
        internal static string OBJECTNAME {
            get {
                return ResourceManager.GetString("OBJECTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PRIMARYKEY}.
        /// </summary>
        internal static string PRIMARYKEY {
            get {
                return ResourceManager.GetString("PRIMARYKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {PROPERTIES}.
        /// </summary>
        internal static string PROPERTIES {
            get {
                return ResourceManager.GetString("PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {STOREDPARAMS}.
        /// </summary>
        internal static string STOREDPARAMS {
            get {
                return ResourceManager.GetString("STOREDPARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {TABLENAME}.
        /// </summary>
        internal static string TABLENAME {
            get {
                return ResourceManager.GetString("TABLENAME", resourceCulture);
            }
        }
    }
}
